### ISSUE TITLE
Missing photo

### ISSUE THREAD

**Issue by StephanieKemna** [dcunhas/agdss#14]
Sometimes, it seems that the photo does not pop up for some reason. Noticed this once yesterday, once again today (today was in poor wifi conditions, do not know if that is related).
The frame is there, and I can draw on it, but I cannot see the actual image.

![agdss1](https://cloud.githubusercontent.com/assets/6518317/17184821/19868480-53e3-11e6-84c5-605ce87070c4.png)
![agdss2](https://cloud.githubusercontent.com/assets/6518317/17184820/19820c5c-53e3-11e6-8496-36f7aa538856.png)

Firefox on Ubuntu 14.04

**Comment by dcunhas** [comment]
This is likely a problem with our images. They have huge areas of white sky, so if that area is cropped, it will display a fully white image. That will hopefully be fixed with a larger window size.

**Comment by StephanieKemna** [comment]
:smile: ok

**Comment by darknight-007** [comment]
Sandeep added a box around image.
