### ISSUE TITLE
Removing/changing size of labels

### ISSUE THREAD

**Issue by StephanieKemna** [dcunhas/agdss#15]
Is there a way to remove labels? If I accidentally click/drag a bit and/or release too early, there's a tiny circle. I don't know how I can change the size (is there a way?), but also don't know how I can remove it when that happens?
A recap of controls at the bottom or something would be useful! :)

**Comment by dcunhas** [comment]
I will add instructions to the main page. Double clicking on a circle should delete it.

**Comment by StephanieKemna** [comment]
:+1:
