### ISSUE TITLE
Cropped Image sometimes is wrong 

### ISSUE THREAD

**Issue by uffles** [dcunhas/agdss#18]
I think the error occurs near the edges of the original image
![error](https://cloud.githubusercontent.com/assets/8302617/17417856/7ee86e5c-5a63-11e6-8382-386b55fd17c5.png)

**Comment by darknight-007** [comment]
Yea, I saw this too, I think same image. 
![image](https://cloud.githubusercontent.com/assets/3958994/17460323/daf0c9ac-5c2e-11e6-94a5-6f4a46aa92ce.png)

**Comment by ShreyasSkandan** [comment]
I just witnessed the same bug. Any thoughts on how to proceed with this image? continue labelling or skip image?
![screen shot 2016-08-12 at 9 44 40 am 2](https://cloud.githubusercontent.com/assets/5595336/17624314/121c70ba-6072-11e6-8ae2-959b9ec0bb9c.png)

**Comment by darknight-007** [comment]
I am not sure how to track the label correspondence for use later, but we should assume we label the oranges we see. kinda like labeling a mosaic of orange images. 

-JD

**Comment by darknight-007** [comment]
Tested, so far no more overlaps. Closing issue.
