### ISSUE TITLE
Circle dragging moves unexpectedly

### ISSUE THREAD

**Issue by dcunhas** [dcunhas/agdss#2]

**Comment by andrewblock01** [comment]
When you try to move an already created circle, the circle immediately shifts such that the tip of the mouse is coincident with the center of the circle even if you start dragging from a position near the edge.  This mainly makes it difficult to move circles near the edge of the photo.

**Comment by dcunhas** [comment]
Fix merged and updated on server. Closed.

**Comment by darknight-007** [comment]
I just verified. Thanks!
