### ISSUE TITLE
Extremely silly but worth considering

### ISSUE THREAD

**Issue by ShreyasSkandan** [dcunhas/agdss#20]
So when I'm labelling fruit and decide to go to the GitHub link, it opens on the same page and could potentially result in me having to re-do some labelling on the image that I was on.

I was wondering if opening the GitHub issue page in a new tab rather than the same tab would be a better option?

**Comment by darknight-007** [comment]
fixed. please check now.

**Comment by ShreyasSkandan** [comment]
Yup, works.
