### ISSUE TITLE
Overlapping fruit label use 

### ISSUE THREAD

**Issue by darknight-007** [dcunhas/agdss#9]
I suppose the raster mask wont capture overlapping labels in a meaningful way? This probably is the first case of moving away from rasters altogether and using SVG directly in ML training code. Thoughts?

**Comment by darknight-007** [comment]
Here is an example: https://www.dropbox.com/s/6uk8rksbavbq7tc/P2379L1070CappleIframe621.jpg.png?dl=0

**Comment by dcunhas** [comment]
It is possible to have rasters with that information (see frame621gray.png at https://www.dropbox.com/home/kumar-prec-ag/temp which does not seem to show up properly on the dropbox preview), but I agree that SVG is better for capturing this information.

**Comment by dcunhas** [comment]
New averages use "overlap-aware" values.
